#!/bin/bash

echo "Enabling NetworkManager..."
sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager
read -sp 'Wi-Fi password: ' password
echo
nmcli dev wifi connect Panget password $password 

echo "Installling packages..."
sudo pacman -Syu --needed - < packages.txt

echo "Installing Paru..."
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

echo "Setting the shell..."
chsh -s /usr/bin/zsh 

echo "Enabling Sway..."
systemctl --user enable sway

echo "Configuring Git..."
git config --global user.name "King Emhyr"
git config --global user.email "kinglanchester@gmail.com"

