#!/bin/zsh

echo "Installling packages..."
sudo pacman -Syu --needed - < packages.txt

echo "Installing Paru..."
rustup default stable
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

echo "Setting the shell..."
chsh -s /usr/bin/zsh 
git clone https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete 
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

echo "Enabling Sway..."
systemctl --user enable sway

echo "Configuring Git..."
git config --global user.name "King Emhyr"
git config --global user.email "kinglanchester@gmail.com"

