theme = "gruvbox_dark_hard"

[editor]
scrolloff                   = 8
mouse                       = true
middle-click-paste          = true
scroll-lines                = 3
shell                       = ["sh", "-c"]
line-number                 = "absolute"
cursorline                  = true
cursorcolumn                = false
auto-completion             = true
auto-format                 = false
idle-timeout                = 400
completion-trigger-len      = 1
auto-info                   = true
auto-pairs                  = true
true-color                  = true
rulers                      = [80]
color-modes                 = true
text-width                  = 80

[editor.soft-wrap]
enable                     = true

[editor.gutters]
layout                      = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width                   = 4

[editor.statusline]
left                        = ["mode", "separator", "file-name", "position", "selections"]
right                       = ["diagnostics", "spinner"]
mode.normal                 = "NORMAL"
mode.insert                 = "INSERT"
mode.select                 = "SELECT"

[editor.lsp]
enable                      = true
display-messages            = true
auto-signature-help         = true
display-inlay-hints         = false
display-signature-help-docs = true
snippets                    = true
goto-reference-include-declaration = true

[editor.cursor-shape]
normal                      = "block"
insert                      = "bar"
select                      = "block"

[editor.file-picker]
hidden                      = true
parents                     = false
ignore                      = true
git-ignore                  = true
git-global                  = false
git-exclude                 = true
# max-depth                   = 

# [editor.auto-pairs]

[editor.search]
smart-case                  = true
wrap-around                 = true

[editor.whitespace]
# render                      = "all"
# characters                  = ""

[editor.whitespace.render]
space                         = "none"
tab                           = "none"
newline                       = "none"
    
[editor.indent-guides]
render                      = false
# character                   = " "
